submit:
	curl -F "token=ESFD_asftB4PfgsXM3qqfw" -F "lab_num=2" -F "file=@dma.py" http://114.212.81.7:9999/upload_code

score:
	curl "http://114.212.81.7:9999/download?token=ESFD_asftB4PfgsXM3qqfw&lab_num=2"
